#INCLUDE <PIC16F877A.INC>

__CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _BROEN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF
    
    
RES_VECT CODE 0x0000
    GOTO    START
    
MAIN_PROG CODE
 
START
    BSP STATUS, RPO
    CLRF TRISB
    CLRF TRISD
    BCF STATUS, RPO
    CLRF PORTB
    CLRF PORTD
    BSF PORTB, 1
    
    
MAIN
    BSF PORTD, 0
    GOTO MAIN
    END
    
    
    